# Generated by Django 2.2.4 on 2019-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='bottom',
            field=models.IntegerField(blank=0, default=0, verbose_name='Bottom'),
        ),
        migrations.AddField(
            model_name='faces',
            name='left',
            field=models.IntegerField(blank=0, default=0, verbose_name='Left'),
        ),
        migrations.AddField(
            model_name='faces',
            name='right',
            field=models.IntegerField(blank=0, default=0, verbose_name='Right'),
        ),
        migrations.AddField(
            model_name='faces',
            name='top',
            field=models.IntegerField(blank=0, default=0, verbose_name='Top'),
        ),
    ]
