# Generated by Django 2.2.4 on 2019-08-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_search', '0003_auto_20190820_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimages',
            name='height',
            field=models.IntegerField(blank=True, default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='md5',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='MD5'),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='state',
            field=models.IntegerField(blank=True, default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='width',
            field=models.IntegerField(blank=True, default=0, verbose_name='Width'),
        ),
    ]
