# Generated by Django 2.2.4 on 2019-08-23 16:54

from django.db import migrations, models
import django_pgcube.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_search', '0004_auto_20190821_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='type_of_metod',
            field=models.IntegerField(blank=True, default=0, verbose_name='Метод кодирование фейса'),
        ),
        migrations.AddField(
            model_name='faces',
            name='vec_high',
            field=django_pgcube.fields.CubeField(default=[], verbose_name='Фейс кодирование 2'),
        ),
        migrations.AddField(
            model_name='faces',
            name='vec_low',
            field=django_pgcube.fields.CubeField(default=[], verbose_name='Фейс кодирование 1'),
        ),
    ]
