# Generated by Django 2.2.4 on 2019-08-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_search', '0005_auto_20190823_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='alt',
            field=models.CharField(default='', max_length=1024, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='images',
            name='tagNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Tag'),
        ),
    ]
