# Generated by Django 2.2.4 on 2019-08-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_search', '0006_auto_20190823_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.CharField(default='', max_length=1024, verbose_name='Адрес'),
        ),
    ]
