# Generated by Django 2.2.4 on 2019-09-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_search', '0008_auto_20190824_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.CharField(default='', max_length=1024, unique=True, verbose_name='Адрес'),
        ),
    ]
