# Generated by Django 2.2.4 on 2019-09-12 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexedSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=512, unique=True, verbose_name='Сайт')),
                ('start_url', models.CharField(default='', max_length=512, unique=True, verbose_name='Начальный адрес а протоколом')),
                ('robotstxt', models.CharField(default='', max_length=2048, verbose_name='robots txt')),
                ('sitemapxml', models.CharField(default='', max_length=512, verbose_name='адрес sitemap.xml')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, help_text='Здесь если что а не в сети', verbose_name='Дата создания')),
                ('lastupdatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний обход')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Проиндексировано?')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.CreateModel(
            name='indexedURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=1024, unique=True, verbose_name='Url')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Проиндексировано?')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, help_text='Здесь если что а не в сети', verbose_name='Дата создания')),
                ('lastupdatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний обход')),
                ('site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fdx_indexer.indexedSite', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
