# Generated by Django 2.2.4 on 2019-08-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "create extension if not exists cube;",
        )
    ]
